meta:
  description: GHActionsSizzleReel
  vendor: '@isaacegg on github <"https://github.com/Isaacegg">'
  maintainer: GH Actions <"https://github.com/Isaacegg/ghactionssizzlereel">
files:
  "/usr/bin/dummytestfile":
    file: my-package
    mode: "0755"
    user: "root"
  "/etc/my-package/testfileconfig":
    file: etc/config
    mode: "0644"
    user: "root"
    keep: true
user: root