name: GitHub Actions Demo
on: [push]
jobs:
  build_site:
    runs-on: nixos-latest
    steps:
    - id: get env setup (checkout)
      uses: actions/checkout@v3
    - id: get env setup (nix-shell setup)
      uses: cachix/install-nix-action@v18
    - id: build site
      uses: workflow/nix-shell-action@v3
      with:
        script: "cd sitebuilder && bash buildsite.sh" 
