name: GitHub Actions Demo (Auto-check changes to codebase)
on:
  pull_request:
    branches:
    - main
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
    - id: get-env-setup_checkout
      uses: actions/checkout@v3
    - id: get-env-setup_nix-shell_setup
      uses: cachix/install-nix-action@v18
    - id: validate-nix-shell
      uses: workflow/nix-shell-action@v3
      with:
        packages: alejandra
        script: "alejandra shell.nix"
    - id: validate-sitebuilder-script
      uses: workflow/nix-shell-action@v3
      with:
        packages: shellcheck
        script: "shellcheck sitebuilder/buildsite.sh" 