name: checking check opt directory on github runner
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check opt directory to see whats inside
      run: sudo apt update -y && sudo apt install tree && sudo tree /opt/
