name: checking check log directory on github runner
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check log directory to see whats inside
      run: sudo tail -n 50 /var/log/*.log
