name: checking check log directory on github runner
 

on: 
  workflow_dispatch:
    inputs:
      friend:
        description: '$'     
        required: true
        default: 'ls'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: sudo {{ cmd }} 
